I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/profile_extension.rpy", line 95, in script
  File "renpy/common/000statements.rpy", line 138, in python
  File "game/profile_extension.rpy", line 95, in python
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/ZERO/Computing/Ren'Py/renpy/execution.py", line 288, in run
    node.execute()
  File "/Users/ZERO/Computing/Ren'Py/renpy/ast.py", line 1531, in execute
    self.call("execute")
  File "/Users/ZERO/Computing/Ren'Py/renpy/ast.py", line 1544, in call
    renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/ZERO/Computing/Ren'Py/renpy/statements.py", line 100, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 138, in execute_play_music
    renpy.music.play(eval(p["file"]),
  File "/Users/ZERO/Computing/Ren'Py/renpy/python.py", line 1331, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/profile_extension.rpy", line 95, in <module>
    play music music_directory[number]
IndexError: list index out of range

Darwin-12.4.0-x86_64-i386-64bit
Ren'Py 6.15.7.374
Secure Self-Attachment Therapy 0.0
